name: example
description: A simple example for string_templates library.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
    string_templates:
      path: ..

dev_dependencies:
  pedantic: ^1.9.0
