name: string_templates
description: A simple library for handling string templates
version: 0.0.2
homepage: https://github.com/navitel-dev/string-templates

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  sprintf: "^4.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
